# fly.toml app configuration file generated for task-flow-api on 2026-02-17T16:28:03-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'task-flow-api'
